services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Port pentru accesul la management UI
      - "5672:5672"    # Portul AMQP pentru RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # utilizator default
      - RABBITMQ_DEFAULT_PASS=admin  # parola pentru utilizator
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # persistă datele RabbitMQ
  watcher:
    build:
      context: .               # același folder unde ai Dockerfile și .csproj
      dockerfile: Dockerfile
    container_name: file-watcher
    depends_on:
      - rabbitmq
    environment:
      # suprascrie cheia din appsettings.json
      NfsWatcher__WatchPath: /watched
    volumes:
      # montează folderul local pe care vrei să-l monitorizezi
      - "/mnt/z/:/watched:ro"
 
volumes:
  rabbitmq_data: